const xmlbuilder = require('xmlbuilder');

const generaXML = (cabecera, detalles) => {
  // Your XML generation logic here
  return xmlbuilder.create('rDE', { version: '1.0', encoding: 'UTF-8' })
  
 
  .att('xmlns', 'http://ekuatia.set.gov.py/sifen/xsd')
  .att('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance')
  .att('xsi:schemaLocation', 'http://ekuatia.set.gov.py/sifen/xsd siRecepDE_v150.xsd')
  .ele('dVerFor', '150').up()
  .ele('DE', { Id: '01800031105011001002724322024072518942776634' })
    .ele('dDVId', '4').up()
    .ele('dFecFirma', '2024-07-25T20:30:40').up()
    .ele('dSisFact', '1').up()
    .ele('gOpeDE')
      .ele('iTipEmi', '1').up()
      .ele('dDesTipEmi', 'Normal').up()
      .ele('dCodSeg', '894277663').up()
    .up()
    .ele('gTimb')
      .ele('iTiDE', '1').up()
      .ele('dDesTiDE', 'Factura electrónica').up()
      .ele('dNumTim', '16032661').up()
      .ele('dEst', '011').up()
      .ele('dPunExp', '001').up()
      .ele('dNumDoc', '0027243').up()
      .ele('dFeIniT', '2022-11-21').up()
    .up()
    .ele('gDatGralOpe')
      .ele('dFeEmiDE', '2024-07-25T10:00:57').up()
      .ele('gOpeCom')
        .ele('iTipTra', '1').up()
        .ele('dDesTipTra', 'Venta de mercadería').up()
        .ele('iTImp', '1').up()
        .ele('dDesTImp', 'IVA').up()
        .ele('cMoneOpe', 'PYG').up()
        .ele('dDesMoneOpe', 'Guarani').up()
      .up()
      .ele('gEmis')
        .ele('dRucEm', '80003110').up()
        .ele('dDVEmi', '5').up()
        .ele('iTipCont', '2').up()
        .ele('dNomEmi', 'CAVALLARO S.A.C.E.I.').up()
        .ele('dNomFanEmi', 'Cavallaro S.A.C.eI.').up()
        .ele('dDirEmi', 'RUTA DEPARTAMENTAL D027 (EX RUTA 1) E/ ISRAEL').up()
        .ele('dNumCas', '1').up()
        .ele('cDepEmi', '12').up()
        .ele('dDesDepEmi', 'CENTRAL').up()
        .ele('cDisEmi', '153').up()
        .ele('dDesDisEmi', 'CAPIATA').up()
        .ele('cCiuEmi', '3568').up()
        .ele('dDesCiuEmi', 'CAPIATA').up()
        .ele('dTelEmi', '0215889000').up()
        .ele('dEmailE', 'cavallaro@cavallaro.com.py').up()
        .ele('gActEco')
          .ele('cActEco', '20130').up()
          .ele('dDesActEco', 'FABRICACIÓN DE PLÁSTICOS Y CAUCHO SINTÉTICO EN FORMAS PRIMARIAS').up()
        .up()
        .ele('gActEco')
          .ele('cActEco', '20931').up()
          .ele('dDesActEco', 'FABRICACIÓN DE JABONES, DETERGENTES Y PREPARADOS DE LIMPIEZA').up()
        .up()
      .up()
      .ele('gDatRec')
        .ele('iNatRec', '1').up()
        .ele('iTiOpe', '1').up()
        .ele('cPaisRec', 'PRY').up()
        .ele('dDesPaisRe', 'Paraguay').up()
        .ele('iTiContRec', '2').up()
        .ele('dRucRec', '5430116').up()
        .ele('dDVRec', '5').up()
        .ele('dNomRec', 'FERNANDEZ, LINO SEBASTIAN').up()
        .ele('dDirRec', 'SANBERNARDINO').up()
        .ele('dNumCasRec', '0').up()
      .up()
    .up()
    .ele('gDtipDE')
      .ele('gCamFE')
        .ele('iIndPres', '1').up()
        .ele('dDesIndPres', 'Operación presencial').up()
      .up()
      .ele('gCamCond')
        .ele('iCondOpe', '1').up()
        .ele('dDCondOpe', 'Contado').up()
        .ele('gPaConEIni')
          .ele('iTiPago', '1').up()
          .ele('dDesTiPag', 'Efectivo').up()
          .ele('dMonTiPag', '110867.000000').up()
          .ele('cMoneTiPag', 'PYG').up()
          .ele('dDMoneTiPag', 'Guarani').up()
        .up()
      .up()
      .ele('gCamItem')
        .ele('dCodInt', '300000033').up()
        .ele('dDesProSer', 'SUAVIZ. CAVALLARO PREMIUM 900 ML. CLASIC').up()
        .ele('cUniMed', '77').up()
        .ele('dDesUniMed', 'UNI').up()
        .ele('dCantProSer', '1.000').up()
        .ele('gValorItem')
          .ele('dPUniProSer', '14790.000000').up()
          .ele('dTotBruOpeItem', '14790.000000').up()
          .ele('gValorRestaItem')
            .ele('dDescItem', '0').up()
            .ele('dPorcDesIt', '0').up()
            .ele('dDescGloItem', '0').up()
            .ele('dAntPreUniIt', '0').up()
            .ele('dAntGloPreUniIt', '0').up()
            .ele('dTotOpeItem', '14790.000000').up()
          .up()
        .up()
        .ele('gCamIVA')
          .ele('iAfecIVA', '1').up()
          .ele('dDesAfecIVA', 'Gravado IVA').up()
          .ele('dPropIVA', '100').up()
          .ele('dTasaIVA', '10').up()
          .ele('dBasGravIVA', '13445.454545').up()
          .ele('dLiqIVAItem', '1344.545455').up()
          .ele('dBasExe', '0').up()
        .up()
      .up()
      .ele('gCamItem')
        .ele('dCodInt', '300000448').up()
        .ele('dDesProSer', 'SUAVIZ. CAVALLARO PREMIUM 900 ML. DELICA').up()
        .ele('cUniMed', '77').up()
        .ele('dDesUniMed', 'UNI').up()
        .ele('dCantProSer', '1.000').up()
        .ele('gValorItem')
          .ele('dPUniProSer', '14790.000000').up()
          .ele('dTotBruOpeItem', '14790.000000').up()
          .ele('gValorRestaItem')
            .ele('dDescItem', '0').up()
            .ele('dPorcDesIt', '0').up()
            .ele('dDescGloItem', '0').up()
            .ele('dAntPreUniIt', '0').up()
            .ele('dAntGloPreUniIt', '0').up()
            .ele('dTotOpeItem', '14790.000000').up()
          .up()
        .up()
        .ele('gCamIVA')
          .ele('iAfecIVA', '1').up()
          .ele('dDesAfecIVA', 'Gravado IVA').up()
          .ele('dPropIVA', '100').up()
          .ele('dTasaIVA', '10').up()
          .ele('dBasGravIVA', '13445.454545').up()
          .ele('dLiqIVAItem', '1344.545455').up()
          .ele('dBasExe', '0').up()
        .up()
      .up()
    .up()
    .ele('gTotSub')
      .ele('dSubExe', '0').up()
      .ele('dSubExo', '0').up()
      .ele('dSub5', '0').up()
      .ele('dSub10', '26890.909090').up()
      .ele('dTotOpe', '26890.909090').up()
      .ele('dIVA5', '0').up()
      .ele('dIVA10', '2689.090910').up()
      .ele('dLiqTotIVA5', '0').up()
      .ele('dLiqTotIVA10', '2689.090910').up()
      .ele('dIVAComi', '2689.090910').up()
      .ele('dTotGralOpe', '29579.000000').up()
    .up()
  .up()
 
.end({ pretty: true });
}

module.exports = {
  generaXML,
};